#!/usr/bin/env bash
# Script that installs Nginx server
apt-get -y install nginx
apt-get -y install nginx
curl -4 icanhazip.com
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
